version: '3'

services:
    coupe:
        build: .
        tty: true
        command: yarn docker:start
        environment:
            - BODY_TYPE=Coupe
            - CHUNK_SIZE=58
        volumes:
            - ./:/opt/app
